baseURL = 'https://blog.rykroon.com/'
languageCode = 'en-us'
title = 'Ryan Kroon'
theme = "PaperMod"

[menu]
  [[menu.main]]
    name = "Tags"
    url = "/tags/"

[params]

  env = 'production' # to enable google analytics, opengraph, twitter-cards and schema.
  description = "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
  author = 'Ryan Kroon'

  defaultTheme = 'auto'
  # disableThemeToggle = true
  ShowShareButtons = false
  ShowReadingTime = true
  disableSpecial1stPost = true
  displayFullLangName = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = false
  ShowAllPagesInArchive = true
  ShowPageNums = true
  ShowToc = true
  # comments = false
  images = [""]
