baseURL = 'https://rykroon.github.io/blog'
languageCode = 'en-us'
title = 'Ryan K'
theme = "PaperMod"

# mainSections=["finance", "economics", "technology"]

[menu]
  [[menu.main]]
    name = "Tags"
    url = "/tags/"

  [[menu.main]]
    name = "Categories"
    url = "/categories/"

[params]

  # https://github.com/adityatelange/hugo-PaperMod/wiki/Variables
  env = 'production' # to enable google analytics, opengraph, twitter-cards and schema.
  description = "Ryan's blog"
  author = 'Ryan K'

  defaultTheme = 'auto'
  # disableThemeToggle = true
  ShowShareButtons = false
  ShowReadingTime = true
  disableSpecial1stPost = true
  displayFullLangName = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = false
  ShowAllPagesInArchive = true
  ShowPageNums = true
  ShowToc = true
  # comments = false
